// ==UserScript==
// @name         BCN Monster Importer
// @namespace    https://github.com/bcn/monster-importer
// @version      2.0.0
// @description  Import homebrew monsters into DnD Beyond from JSON — main form + Languages/Senses/Skills/Movement sub-pages
// @author       Bill Martin <wlm2048@gmail.com>
// @match        https://www.dndbeyond.com/homebrew/creations/create-monster
// @match        https://www.dndbeyond.com/homebrew/creations/create-monster/create
// @match        https://www.dndbeyond.com/homebrew/creations/monsters/*/edit
// @match        https://www.dndbeyond.com/monster/senses/create/*
// @match        https://www.dndbeyond.com/monster/skills/create/*
// @match        https://www.dndbeyond.com/monster/movement/create/*
// @match        https://www.dndbeyond.com/entity/language/create/*
// @grant        none
// ==/UserScript==

(function () {
    'use strict';

    // !! Generated by build.js — edit files in src/ instead of this file !!

    // Guard against Tampermonkey injecting this multiple times on the same page
    // (happens when TinyMCE editor init triggers extra document events).
    if (window.__bcnImporterLoaded) return;
    window.__bcnImporterLoaded = true;

    // Guard against running inside a TinyMCE iframe — we only want the top frame.
    if (window !== window.top) return;

    // =========================================================================
    // SESSION STORAGE KEY
    // Used to pass the JSON payload across page navigations.
    // =========================================================================
    const SS_KEY = 'bcn_importer_payload';

    // =========================================================================
    // SELECT OPTION VALUE MAPS
    // These numeric IDs are taken from the live DnD Beyond HTML.
    // If DnD Beyond updates their form, re-confirm each map using dumpFormFields()
    // and cross-check against the relevant <select> element on the live page.
    // =========================================================================

    const MONSTER_TYPES = {
        aberration: 1, beast: 2, celestial: 3, construct: 4,
        dragon: 6, elemental: 7, fey: 8, fiend: 9, giant: 10,
        humanoid: 11, monstrosity: 13, ooze: 14, plant: 15,
        undead: 16, unknown: 17
    };

    const SIZES = {
        tiny: 2, small: 3, medium: 4, 'medium or small': 10,
        large: 5, huge: 6, gargantuan: 7,
        sm: 3, med: 4, lg: 5
    };

    const ALIGNMENTS = {
        'lawful good': 1, 'neutral good': 2, 'chaotic good': 3,
        'lawful neutral': 4, neutral: 5, 'chaotic neutral': 6,
        'lawful evil': 7, 'neutral evil': 8, 'chaotic evil': 9,
        'any alignment': 11, 'unaligned': 10,
        'any evil alignment': 13, 'any good alignment': 14,
        'any chaotic alignment': 15, 'any non-lawful alignment': 19,
        'any non-good alignment': 18
    };

    const CR_VALUES = {
        '0': 1, '1/8': 2, '1/4': 3, '1/2': 4,
        '1': 5, '2': 6, '3': 7, '4': 8, '5': 9,
        '6': 10, '7': 11, '8': 12, '9': 13, '10': 14,
        '11': 15, '12': 16, '13': 17, '14': 18, '15': 19,
        '16': 20, '17': 21, '18': 22, '19': 23, '20': 24,
        '21': 25, '22': 26, '23': 27, '24': 29, '25': 30,
        '26': 31, '27': 32, '28': 33, '29': 34, '30': 35
    };

    const SAVING_THROWS = { str: 1, dex: 2, con: 3, int: 4, wis: 5, cha: 6 };

    const DAMAGE_ADJUSTMENTS = {
        'bludgeoning - resistance': 1,
        'piercing - resistance': 2,
        'slashing - resistance': 3,
        'lightning - resistance': 4,
        'thunder - resistance': 5,
        'poison - resistance': 6,
        'cold - resistance': 7,
        'radiant - resistance': 8,
        'fire - resistance': 9,
        'necrotic - resistance': 10,
        'acid - resistance': 11,
        'psychic - resistance': 12,
        'bludgeoning, piercing, and slashing from nonmagical attacks - resistance': 13,
        'bludgeoning, piercing, and slashing from nonmagical attacks that aren\'t silvered - resistance': 14,
        'bludgeoning, piercing, and slashing from nonmagical attacks that aren\'t adamantine - resistance': 15,
        'bludgeoning - immunity': 17,
        'piercing - immunity': 18,
        'slashing - immunity': 19,
        'lightning - immunity': 20,
        'thunder - immunity': 21,
        'poison - immunity': 22,
        'cold - immunity': 23,
        'radiant - immunity': 24,
        'fire - immunity': 25,
        'necrotic - immunity': 26,
        'acid - immunity': 27,
        'psychic - immunity': 28,
        'bludgeoning, piercing, and slashing from nonmagical attacks - immunity': 29,
        'bludgeoning, piercing, and slashing from nonmagical attacks that aren\'t silvered - immunity': 30,
        'bludgeoning, piercing, and slashing from nonmagical attacks that aren\'t adamantine - immunity': 31,
        'bludgeoning - vulnerability': 33,
        'piercing - vulnerability': 34,
        'slashing - vulnerability': 35,
        'cold - vulnerability': 39,
        'fire - vulnerability': 41,
        'necrotic - vulnerability': 42,
        'force - resistance': 47,
        'force - immunity': 48,
        'all - resistance': 53,
        'all - immunity': 89,
    };

    const CONDITION_IMMUNITIES = {
        blinded: 1, charmed: 2, deafened: 3, exhaustion: 4,
        frightened: 5, grappled: 6, incapacitated: 7, invisible: 8,
        paralyzed: 9, petrified: 10, poisoned: 11, prone: 12,
        restrained: 13, stunned: 14, unconscious: 15
    };

    const ENVIRONMENTS = {
        any: 13, arctic: 1, coastal: 2, desert: 3, forest: 4,
        grassland: 5, hill: 6, mountain: 7, swamp: 8, underdark: 9,
        underwater: 10, urban: 11,
        'planar (shadowfell)': 12, 'planar (abyss)': 18,
        'planar (nine hells)': 19, 'planar (feywild)': 21,
    };

    // Sense type → DnD Beyond option value
    // Confirmed from live HTML: field-sense, options 1–5
    const SENSE_TYPES = {
        'blindsight': 1,
        'darkvision': 2,
        'tremorsense': 3,
        'truesight': 4,
        'unknown': 5,
        "devil's sight": 5, 'devils sight': 5,
    };

    // Skill name → DnD Beyond skill ID
    // Confirmed from live HTML: field-skill select
    const SKILL_IDS = {
        acrobatics: 3, 'animal handling': 11, arcana: 6, athletics: 2,
        deception: 16, history: 7, insight: 12, intimidation: 17,
        investigation: 8, medicine: 13, nature: 9, perception: 14,
        performance: 18, persuasion: 19, religion: 10, 'sleight of hand': 4,
        stealth: 5, survival: 15
    };

    // Movement type → option value
    // Confirmed from live HTML: field-movement-type select
    const MOVEMENT_TYPES = {
        burrow: 2, climb: 3, fly: 4, swim: 5, walk: 1,
    };

    // Language name → DnD Beyond language ID
    // Confirmed from live HTML: field-language select
    const LANGUAGE_IDS = {
        common: 1, dwarvish: 2, elvish: 3, giant: 4, gnomish: 5,
        goblin: 6, halfling: 7, orc: 8, abyssal: 9, celestial: 10,
        draconic: 11, 'deep speech': 12, infernal: 13, primordial: 14,
        sylvan: 15, undercommon: 16, druidic: 23, telepathy: 18,
        aquan: 19, auran: 20, ignan: 21, terran: 22,
        "thieves' cant": 46, 'thieves cant': 46,
        all: 35, 'all languages': 35, none: 128,
        // Expanded list from live HTML
        aarakocra: 36, aartuk: 88, abanasinian: 89, aglarondan: 151,
        aklo: 146, alzhedo: 152, angulotl: 121, ankeshelian: 126,
        archosauric: 167, birdfolk: 102, 'black speech': 129,
        'blink dog': 33, bothii: 51, bullywug: 38, caligni: 147,
        capran: 138, cervan: 103, chessentan: 153, chondathan: 154,
        'citlanés': 74, 'common sign language': 127,
        'communication spores': 166, daelkyr: 62, daemonic: 148,
        dalish: 130, damaran: 155, dara: 142, darakhul: 109,
        demodand: 101, derro: 110, djaynaian: 75, dohwar: 86,
        dunlendish: 136, eluran: 139, eonic: 111, ergot: 90,
        erina: 112, 'feather speech': 104, 'giant eagle': 24,
        'giant elk': 25, 'giant owl': 26, gibberling: 123, gith: 39,
        gnoll: 27, godstongue: 76, grell: 40, grippli: 70, grung: 47,
        hadozee: 87, halri: 77, hedge: 105, 'hook horror': 41,
        howler: 143, "huginn's speech": 124, 'ice toad': 55,
        iluskan: 156, istarian: 91, ixitxachitl: 52, jerbeen: 106,
        kenderspeak: 92, kharolian: 93, khur: 94, khuzdul: 131,
        kothian: 95, kraul: 60, kruthik: 73, "kuran'zoi": 122,
        lantanese: 157, lemurfolk: 113, leonin: 69, loxodan: 114,
        loxodon: 59, mapach: 107, marquesian: 67, maynah: 78,
        midani: 158, millitaur: 115, minotaur: 58, modron: 42,
        mulhorandi: 159, 'naku naku': 144, naush: 68, necril: 149,
        nerakese: 96, netherese: 54, nordmaarian: 97,
        'northern tongue': 125, "n'warian": 79, ogre: 98, olman: 56,
        orkish: 132, otyugh: 28, quirapu: 80, quori: 57, rashemi: 160,
        ravenfolk: 116, reghedjic: 161, riedran: 64, sahuagin: 29,
        sensan: 81, sespech: 162, shankhi: 82, sindarin: 133,
        'skin cant': 165, skitterwidget: 71, slaad: 37, solamnic: 99,
        sphinx: 30, swallybog: 141, thayan: 53, 'thri-kreen': 43,
        tilia: 140, tletlahtolli: 83, tlincalli: 48, torum: 145,
        tosculi: 117, troglodyte: 44, trollkin: 118, turmic: 163,
        'umber hulk': 45, umbral: 119, untheric: 164, varisian: 150,
        vedalken: 61, vegepygmy: 49, 'void speech': 120, vulpin: 108,
        'warg-speech': 134, westron: 135, 'winter wolf': 31, worg: 32,
        xingyu: 84, yeti: 34, yikaria: 50, zabaani: 85, zemnian: 66,
        ziklight: 72,
    };

    // =========================================================================
    // UTILITY HELPERS
    // =========================================================================

    function normalise(str) {
        return (str || '').toString().trim().toLowerCase();
    }

    function setInput(id, value) {
        const el = document.getElementById(id);
        if (!el) { console.warn('[BCN] input not found:', id); return false; }
        el.value = value;
        el.dispatchEvent(new Event('input', { bubbles: true }));
        el.dispatchEvent(new Event('change', { bubbles: true }));
        return true;
    }

    function setSelect(id, value) {
        const el = document.getElementById(id);
        if (!el) { console.warn('[BCN] select not found:', id); return false; }
        el.value = value;
        el.dispatchEvent(new Event('change', { bubbles: true }));
        return true;
    }

    function setCheckbox(realId, fakeContainerId, checked) {
        const real = document.getElementById(realId);
        if (!real) return;
        real.checked = checked;
        real.dispatchEvent(new Event('change', { bubbles: true }));
        const fakeContainer = fakeContainerId ? document.getElementById(fakeContainerId) : null;
        if (fakeContainer) {
            if (checked) fakeContainer.classList.add('checked');
            else fakeContainer.classList.remove('checked');
        }
    }

    function setSelect2(selectId, numericValues) {
        const el = document.getElementById(selectId);
        if (!el) { console.warn('[BCN] select2 not found:', selectId); return; }
        const jqEl = window.jQuery ? jQuery('#' + selectId) : null;
        if (jqEl && jqEl.data('select2')) {
            jqEl.val(numericValues.map(String)).trigger('change');
        } else {
            Array.from(el.options).forEach(opt => {
                opt.selected = numericValues.map(String).includes(opt.value);
            });
            el.dispatchEvent(new Event('change', { bubbles: true }));
        }
    }

    // Run callback once TinyMCE has initialised all its editors, or immediately if already done.
    function whenTinyMCEReady(cb) {
        if (window.tinyMCE && tinyMCE.editors && tinyMCE.editors.length > 0) {
            cb(); return;
        }
        const poll = setInterval(() => {
            if (window.tinyMCE && tinyMCE.editors && tinyMCE.editors.length > 0) {
                clearInterval(poll);
                setTimeout(cb, 200); // small extra settle delay
            }
        }, 200);
        setTimeout(() => { clearInterval(poll); cb(); }, 5000); // fallback
    }

    function setRichText(fieldId, html) {
        // Always write — empty string clears DnD Beyond's placeholder text.
        const content = html || '';
        const textarea = document.getElementById(fieldId);
        if (!textarea) { console.warn('[BCN] richtext not found:', fieldId); return; }

        // Always set the underlying textarea value — this covers fields that are
        // disabled (legendary, mythic, lair) where TinyMCE has no active instance.
        textarea.value = content;
        textarea.dispatchEvent(new Event('change', { bubbles: true }));

        // Also update the live TinyMCE editor if one exists for this field
        if (window.tinyMCE) {
            const editor = tinyMCE.get(fieldId);
            if (editor) { editor.setContent(content); editor.isNotDirty = false; }
        }
    }

    // Scan all <select> elements for an option whose text contains `needle`.
    // Returns { el, value } or null.
    function findSelectByOptionText(needle) {
        const n = normalise(needle);
        for (const sel of document.querySelectorAll('select')) {
            for (const opt of sel.options) {
                if (normalise(opt.text).includes(n)) return { el: sel, value: opt.value };
            }
        }
        return null;
    }

    // Log all form fields to console — invaluable when a sub-page has unknown IDs.
    function dumpFormFields() {
        console.group('[BCN] Form field inventory for: ' + window.location.pathname);
        document.querySelectorAll('input[id], select[id], textarea[id]').forEach(el => {
            const val = el.type === 'select-one' || el.type === 'select-multiple'
                ? `selected="${el.value}"` : `value="${el.value}"`;
            console.log(`  ${el.tagName}#${el.id} [${el.type || 'select'}] ${val}`);
        });
        console.groupEnd();
    }

    function showBanner(message, colour) {
        document.getElementById('bcn-banner')?.remove();
        const banner = document.createElement('div');
        banner.id = 'bcn-banner';
        banner.style.cssText = `
            position:fixed;top:16px;left:50%;transform:translateX(-50%);
            background:${colour || '#1a6b2e'};color:#fff;padding:12px 28px;
            border-radius:6px;font-size:14px;font-weight:600;
            z-index:99999;box-shadow:0 4px 16px rgba(0,0,0,0.5);
            max-width:700px;text-align:center;line-height:1.5;pointer-events:none;
        `;
        banner.textContent = message;
        document.body.appendChild(banner);
        if (colour !== '#c0392b') setTimeout(() => banner.remove(), 7000);
    }

    // Persistent prompt shown on sub-pages — stays until the user clicks Save.
    // Avoids DnD Beyond's anti-automation login redirect triggered by scripted submits.
    function showSavePrompt(statusText) {
        document.getElementById('bcn-save-prompt')?.remove();
        const prompt = document.createElement('div');
        prompt.id = 'bcn-save-prompt';
        prompt.style.cssText = `
            position:fixed;top:0;left:0;right:0;
            background:#1a3a5c;color:#fff;padding:14px 24px;
            display:flex;align-items:center;justify-content:space-between;gap:16px;
            z-index:99999;box-shadow:0 2px 12px rgba(0,0,0,0.5);
            font-family:sans-serif;font-size:13px;
        `;
        prompt.innerHTML = `
            <span style="flex:1;line-height:1.5;">
                <strong style="color:#7dd;">⬇ BCN Importer</strong> — ${statusText}
            </span>
            <button id="bcn-save-now-btn" style="
                background:#1a6b2e;color:#fff;border:none;padding:10px 22px;
                border-radius:4px;cursor:pointer;font-size:14px;font-weight:700;
                white-space:nowrap;flex-shrink:0;
            ">Click Save to continue →</button>
        `;
        document.body.appendChild(prompt);

        // Wire the button to the page's actual Save button so the user only needs
        // to click our clearly-visible button rather than hunting for DnD Beyond's
        document.getElementById('bcn-save-now-btn').addEventListener('click', () => {
            prompt.remove();
            if (window.tinyMCE) { try { tinyMCE.triggerSave(); } catch(e) {} }
            const saveBtn = document.querySelector('button[type=submit], input[type=submit]')
                         || document.querySelector('button.button');
            if (saveBtn) saveBtn.click();
        });
    }

    // Click the submit button on the page's main form.
    function submitPageForm() {
        if (window.tinyMCE) { try { tinyMCE.triggerSave(); } catch (e) {} }
        const form = document.querySelector('form');
        if (!form) { console.error('[BCN] No form to submit'); return; }
        const btn = form.querySelector('button[type=submit], input[type=submit]')
                 || form.querySelector('button.button')
                 || form.querySelector('button');
        if (btn) btn.click(); else form.submit();
    }

    // =========================================================================
    // SESSION STORAGE — persist the queue across page loads
    //
    // Payload shape stored in sessionStorage:
    // {
    //   data:      { ...original monster JSON, with senses/skills/movement/languages
    //                arrays consumed one entry at a time as sub-pages complete },
    //   monsterId: "6398993",
    //   entityId:  "779871897",   // from language link; null if not found
    //   editUrl:   "https://www.dndbeyond.com/homebrew/creations/monsters/…/edit",
    //   queue:     ["senses","skills","movement","languages"],  // remaining page types
    //   done:      [],            // page types already completed
    // }
    // =========================================================================

    function loadPayload() {
        try { return JSON.parse(sessionStorage.getItem(SS_KEY)); } catch (e) { return null; }
    }
    function savePayload(p) { sessionStorage.setItem(SS_KEY, JSON.stringify(p)); }
    function clearPayload() { sessionStorage.removeItem(SS_KEY); }

    // Build initial queue — only sub-page types that have data
    function buildQueue(data) {
        const q = [];
        if (Array.isArray(data.senses)    && data.senses.length)    q.push('senses');
        if (Array.isArray(data.skills)    && data.skills.length)    q.push('skills');
        if (Array.isArray(data.movement)  && data.movement.length)  q.push('movement');
        if (Array.isArray(data.languages) && data.languages.length) q.push('languages');
        return q;
    }

    // Pull monster ID and entity ID out of the sub-page links on the edit page
    function extractIds() {
        const langLink = document.querySelector('a[href*="/entity/language/create/"]');
        if (langLink) {
            const m = langLink.href.match(/\/entity\/language\/create\/(\d+)-(\d+)/);
            if (m) return { monsterId: m[1], entityId: m[2] };
        }
        const sensesLink = document.querySelector('a[href*="/monster/senses/create/"]')
                        || document.querySelector('a[href*="/monster/skills/create/"]')
                        || document.querySelector('a[href*="/monster/movement/create/"]');
        if (sensesLink) {
            const m = sensesLink.href.match(/\/monster\/\w+\/create\/(\d+)/);
            if (m) return { monsterId: m[1], entityId: null };
        }
        return { monsterId: null, entityId: null };
    }

    // Navigate to the first URL in the queue
    function navigateToNext(payload) {
        const next = payload.queue[0];
        const { monsterId, entityId } = payload;

        const urls = {
            senses:    `https://www.dndbeyond.com/monster/senses/create/${monsterId}`,
            skills:    `https://www.dndbeyond.com/monster/skills/create/${monsterId}`,
            movement:  `https://www.dndbeyond.com/monster/movement/create/${monsterId}`,
            languages: `https://www.dndbeyond.com/entity/language/create/${monsterId}-${entityId}`,
        };

        const url = urls[next];
        if (!url || url.includes('undefined') || url.includes('null')) {
            const msg = next === 'languages' && !entityId
                ? `Cannot navigate to languages — entity ID not found. Open the edit page once, then re-run.`
                : `Cannot build URL for "${next}" — monsterId: ${monsterId}`;
            showBanner('⚠ ' + msg, '#c0392b');
            console.error('[BCN]', msg);
            return;
        }

        savePayload(payload);
        showBanner(`⏳ Moving to ${next} page…`, '#2c5aa0');
        window.location.href = url;
    }

    // Called after a sub-page type is fully done (or empty): remove from queue and advance
    function advanceQueue(payload) {
        if (payload.queue.length === 0) {
            clearPayload();
            showBanner('✓ All done! Returning to monster edit page…', '#1a6b2e');
            setTimeout(() => { window.location.href = payload.editUrl; }, 1500);
        } else {
            navigateToNext(payload);
        }
    }

    // =========================================================================
    // MAIN FORM FILL
    // =========================================================================

    function fillMainForm(data) {
        const errors = [];

        setSelect('field-stat-block-type', normalise(data.statBlockType) === '5e' ? '0' : '1');

        if (data.name)    setInput('field-Name', data.name);
        if (data.version !== undefined) setInput('field-version', data.version);

        const typeVal = MONSTER_TYPES[normalise(data.monsterType)];
        if (typeVal) setSelect('field-monster-type', String(typeVal));
        else if (data.monsterType) errors.push(`Unknown monsterType: "${data.monsterType}"`);

        const sizeVal = SIZES[normalise(data.size)];
        if (sizeVal) setSelect('field-size', String(sizeVal));
        else if (data.size) errors.push(`Unknown size: "${data.size}"`);

        if (data.alignment) {
            const v = ALIGNMENTS[normalise(data.alignment)];
            if (v) setSelect('field-alignment', String(v));
            else errors.push(`Unknown alignment: "${data.alignment}"`);
        }

        if (data.cr !== undefined) {
            const v = CR_VALUES[String(data.cr).trim()];
            if (v) setSelect('field-challenge-rating', String(v));
            else errors.push(`Unknown CR: "${data.cr}"`);
        }

        // Defer all rich text writes until TinyMCE editors are fully initialised.
        // If we write before TinyMCE is ready the content goes into the textarea but
        // TinyMCE overwrites it with its placeholder when it initialises.
        whenTinyMCEReady(() => {
            setRichText('field-special-traits-description-wysiwyg',         data.traits          || '');
            setRichText('field-actions-description-wysiwyg',                data.actions         || '');
            setRichText('field-bonus-actions-description-wysiwyg',          data.bonusActions    || '');
            setRichText('field-reactions-description-wysiwyg',              data.reactions       || '');
            setRichText('field-monster-characteristics-description-wysiwyg',data.characteristics || '');
            // Always clear the conditional rich text fields to remove placeholders,
            // even when the monster isn't legendary/mythic/lair.
            setRichText('field-legendary-actions-description-wysiwyg',
                (data.isLegendary && data.legendaryActions) ? data.legendaryActions : '');
            setRichText('field-mythic-actions-description-wysiwyg',
                (data.isMythic && data.mythicActions) ? data.mythicActions : '');
            setRichText('field-lair-description-wysiwyg',
                (data.hasLair && data.lairDescription) ? data.lairDescription : '');
        });

        if (data.ac              !== undefined) setInput('field-armor-class',         data.ac);
        if (data.acType          !== undefined) setInput('field-armor-class-type',    data.acType);
        if (data.initiativeBonus !== undefined) setInput('field-initiative-bonus',    data.initiativeBonus);
        if (data.passivePerception !== undefined) setInput('field-passive-perception', data.passivePerception);
        if (data.hp              !== undefined) setInput('field-average-hit-points',  data.hp);
        if (data.hpDieCount      !== undefined) setInput('field-hit-points-die-count',data.hpDieCount);
        if (data.hpDieValue      !== undefined) setSelect('field-hit-points-die-value', String(data.hpDieValue));
        if (data.hpModifier      !== undefined) setInput('field-hit-points-modifier', data.hpModifier);

        if (data.str !== undefined) setInput('field-strength',    data.str);
        if (data.dex !== undefined) setInput('field-dexterity',   data.dex);
        if (data.con !== undefined) setInput('field-constitution', data.con);
        if (data.int !== undefined) setInput('field-intelligence', data.int);
        if (data.wis !== undefined) setInput('field-wisdom',      data.wis);
        if (data.cha !== undefined) setInput('field-charisma',    data.cha);

        if (Array.isArray(data.savingThrows) && data.savingThrows.length) {
            setSelect2('field-monster-saving-throw',
                data.savingThrows.map(s => SAVING_THROWS[normalise(s)]).filter(Boolean));
        }

        if (data.saveBonusStr !== undefined) setInput('field-strength-save-bonus',     data.saveBonusStr);
        if (data.saveBonusDex !== undefined) setInput('field-dexterity-save-bonus',    data.saveBonusDex);
        if (data.saveBonusCon !== undefined) setInput('field-constitution-save-bonus', data.saveBonusCon);
        if (data.saveBonusInt !== undefined) setInput('field-intelligence-save-bonus', data.saveBonusInt);
        if (data.saveBonusWis !== undefined) setInput('field-wisdom-save-bonus',       data.saveBonusWis);
        if (data.saveBonusCha !== undefined) setInput('field-charisma-save-bonus',     data.saveBonusCha);

        if (Array.isArray(data.damageAdjustments) && data.damageAdjustments.length) {
            const vals = data.damageAdjustments.map(s => DAMAGE_ADJUSTMENTS[normalise(s)]).filter(Boolean);
            const unk  = data.damageAdjustments.filter(s => !DAMAGE_ADJUSTMENTS[normalise(s)]);
            if (unk.length) errors.push(`Unknown damage adjustments: ${unk.join(', ')}`);
            setSelect2('field-damage-adjustment', vals);
        }

        if (Array.isArray(data.conditionImmunities) && data.conditionImmunities.length) {
            setSelect2('field-condition-immunity',
                data.conditionImmunities.map(s => CONDITION_IMMUNITIES[normalise(s)]).filter(Boolean));
        }

        if (Array.isArray(data.environments) && data.environments.length) {
            setSelect2('field-monster-environments',
                data.environments.map(s => ENVIRONMENTS[normalise(s)]).filter(Boolean));
        }

        if (data.gear         !== undefined) setInput('field-gear-description', data.gear);
        if (data.languageNote !== undefined) setInput('field-languages-note',   data.languageNote);

        setCheckbox('field-is-legendary', 'fc-fake-is-legendary', !!data.isLegendary);
        setCheckbox('field-is-mythic', 'fc-fake-is-mythic', !!data.isMythic);
        setCheckbox('field-has-lair', 'fc-fake-has-lair', !!data.hasLair);

        return errors;
    }

    // =========================================================================
    // SUB-PAGE FILLERS
    // Each filler fills ONE entry on the current sub-page and returns true/false.
    // After a successful fill the caller saves the payload and submits the form.
    // DnD Beyond redirects back to the same create URL so the script fires again
    // for the next item automatically.
    // =========================================================================

    // /monster/senses/create/{monsterId}
    // Confirmed field IDs from live HTML:
    //   field-sense      (Select2: 1=Blindsight 2=Darkvision 3=Tremorsense 4=Truesight 5=Unknown)
    //   field-sense-note (text input for "60 ft." etc.)
    // Note: no "Devil's Sight" option exists — use type "unknown" for that.
    function fillSensePage(sense) {
        const typeVal = SENSE_TYPES[normalise(sense.type)];
        if (!typeVal) {
            showBanner(`⚠ Unknown sense type: "${sense.type}". Valid: blindsight, darkvision, tremorsense, truesight, unknown`, '#c0392b');
            return false;
        }
        // field-sense is a Select2 — must use jQuery .val().trigger('change')
        const jqEl = window.jQuery ? jQuery('#field-sense') : null;
        if (jqEl && jqEl.length && jqEl.data('select2')) {
            jqEl.val(String(typeVal)).trigger('change');
        } else {
            // Fallback: set underlying <select> directly
            if (!setSelect('field-sense', String(typeVal))) {
                const found = findSelectByOptionText(sense.type);
                if (!found) { showBanner(`⚠ field-sense not found. See console.`, '#c0392b'); return false; }
                found.el.value = found.value;
                found.el.dispatchEvent(new Event('change', { bubbles: true }));
            }
        }
        if (sense.notes !== undefined) setInput('field-sense-note', sense.notes);
        return true;
    }

    // /monster/skills/create/{monsterId}
    // Confirmed field IDs from live HTML:
    //   field-skill           (Select2: skill IDs confirmed above)
    //   field-value           (text: flat bonus, e.g. "5" — leave blank to use proficiency auto-calc)
    //   field-additional-bonus (text: extra bonus on top, usually blank)
    // NOTE: there is NO proficiency type select. DnD Beyond auto-calculates from CR.
    // Use field-value only if you want to hard-override the displayed bonus.
    function fillSkillPage(skill) {
        const skillId = SKILL_IDS[normalise(skill.name)];
        if (!skillId) {
            showBanner(`⚠ Unknown skill: "${skill.name}". Check SKILL_IDS map.`, '#c0392b');
            return false;
        }
        // field-skill is a Select2
        const jqEl = window.jQuery ? jQuery('#field-skill') : null;
        if (jqEl && jqEl.length && jqEl.data('select2')) {
            jqEl.val(String(skillId)).trigger('change');
        } else {
            if (!setSelect('field-skill', String(skillId))) {
                const found = findSelectByOptionText(skill.name);
                if (!found) { showBanner(`⚠ field-skill not found. See console.`, '#c0392b'); return false; }
                found.el.value = found.value;
                found.el.dispatchEvent(new Event('change', { bubbles: true }));
            }
        }
        // Optional flat bonus override — only set if explicitly provided
        if (skill.value !== undefined)           setInput('field-value', skill.value);
        if (skill.additionalBonus !== undefined) setInput('field-additional-bonus', skill.additionalBonus);
        return true;
    }

    // /monster/movement/create/{monsterId}
    // Confirmed field IDs from live HTML:
    //   field-movement-type (select: 1=Walk 2=Burrow 3=Climb 4=Fly 5=Swim)
    //   field-speed         (text: numeric speed in feet)
    //   field-note          (textarea: optional note e.g. "(hover)")
    // NOTE: no hover checkbox — use notes: "(hover)" for hover fly speed.
    function fillMovementPage(movement) {
        const typeVal = MOVEMENT_TYPES[normalise(movement.type)];
        if (!typeVal) {
            showBanner(`⚠ Unknown movement type: "${movement.type}". Valid: walk, burrow, climb, fly, swim`, '#c0392b');
            return false;
        }
        if (!setSelect('field-movement-type', String(typeVal))) {
            const found = findSelectByOptionText(movement.type);
            if (!found) { showBanner(`⚠ field-movement-type not found. See console.`, '#c0392b'); return false; }
            found.el.value = found.value;
            found.el.dispatchEvent(new Event('change', { bubbles: true }));
        }
        if (movement.speed !== undefined) setInput('field-speed', movement.speed);
        if (movement.notes !== undefined) setInput('field-note', movement.notes);
        return true;
    }

    // /entity/language/create/{monsterId}-{entityId}
    // Confirmed field IDs from live HTML:
    //   field-language (Select2: full language list with confirmed IDs above)
    //   field-note     (text: free-form note, e.g. "but does not speak")
    // NOTE: no separate "speaks/understands" field — just the language + a note.
    function fillLanguagePage(language) {
        const langId = LANGUAGE_IDS[normalise(language.name)];
        let set = false;
        if (langId) {
            // field-language is a Select2
            const jqEl = window.jQuery ? jQuery('#field-language') : null;
            if (jqEl && jqEl.length && jqEl.data('select2')) {
                jqEl.val(String(langId)).trigger('change');
                set = true;
            } else {
                set = setSelect('field-language', String(langId));
            }
        }
        if (!set) {
            const found = findSelectByOptionText(language.name);
            if (found) {
                found.el.value = found.value;
                found.el.dispatchEvent(new Event('change', { bubbles: true }));
                set = true;
            }
        }
        if (!set) {
            showBanner(`⚠ Could not find language: "${language.name}". Check LANGUAGE_IDS map.`, '#c0392b');
            return false;
        }
        // field-note holds any free-form note ("but does not speak", etc.)
        // language.description is also accepted as an alias for note
        const noteVal = language.notes !== undefined ? language.notes
                      : language.description !== undefined ? language.description
                      : undefined;
        if (noteVal !== undefined) setInput('field-note', noteVal);
        return true;
    }

    // =========================================================================
    // SUB-PAGE ORCHESTRATION
    // On each sub-page: fill the first item in the array, pop it, submit.
    // DnD Beyond sends us back to the same create URL, so we loop until empty.
    // When array is empty, move to the next queue entry (or back to edit page).
    // =========================================================================

    function runSubPage(payload) {
        const path = window.location.pathname;
        let pageType = null;
        if (path.includes('/monster/senses/create/'))   pageType = 'senses';
        if (path.includes('/monster/skills/create/'))   pageType = 'skills';
        if (path.includes('/monster/movement/create/')) pageType = 'movement';
        if (path.includes('/entity/language/create/'))  pageType = 'languages';
        if (!pageType) return;

        const items = payload.data[pageType];

        if (!Array.isArray(items) || items.length === 0) {
            // Nothing (or nothing left) for this type — advance
            payload.queue.shift();
            payload.done = payload.done || [];
            payload.done.push(pageType);
            advanceQueue(payload);
            return;
        }

        const item      = items[0];
        const remaining = items.slice(1);

        let filled = false;
        if (pageType === 'senses')    filled = fillSensePage(item);
        if (pageType === 'skills')    filled = fillSkillPage(item);
        if (pageType === 'movement')  filled = fillMovementPage(item);
        if (pageType === 'languages') filled = fillLanguagePage(item);

        if (!filled) {
            // Error banner already shown — stall so the user can see it.
            // Leave payload intact so they can manually fix and retry.
            return;
        }

        // Update payload with remaining items
        payload.data[pageType] = remaining;

        if (remaining.length === 0) {
            payload.queue.shift();
            payload.done = payload.done || [];
            payload.done.push(pageType);
        }

        savePayload(payload);

        // Build the "what's next" summary
        const leftInType = remaining.length;
        const nextUp = payload.queue.length > 0
            ? `Next: ${payload.queue.join(' → ')}`
            : 'Last entry — will return to edit page after save.';
        const itemSummary = leftInType > 0
            ? `${leftInType} more ${pageType} to go after this.`
            : `All ${pageType} done.`;

        // Show a persistent save prompt — user clicks Save themselves to avoid
        // DnD Beyond's anti-automation login redirects
        showSavePrompt(`Fields filled. ${itemSummary} ${nextUp}`);
    }

    // =========================================================================
    // MAIN FORM — full import + save + sub-page chain
    // =========================================================================

    function startImport(data) {
        const errors = fillMainForm(data);
        const { monsterId, entityId } = extractIds();
        const queue = buildQueue(data);

        if (errors.length) {
            alert('[BCN] Warnings:\n' + errors.map(e => '• ' + e).join('\n') + '\n\nAll other fields filled.');
        }

        if (queue.length === 0) {
            showBanner('✓ Form filled. Review then click Save Changes.');
            return;
        }

        if (!monsterId) {
            showBanner('⚠ Sub-page links not found — is this monster saved yet? Save it once manually, then re-import.', '#c0392b');
            return;
        }

        // Stash payload and prompt — user clicks Save, DnD Beyond redirects to edit,
        // script picks up the queue on arrival
        const payload = {
            data, monsterId, entityId,
            editUrl: window.location.href,
            queue, done: [],
        };
        savePayload(payload);
        showSavePrompt(`Form filled. Will continue to: ${queue.join(' → ')} after save.`);
    }

    // =========================================================================
    // SAMPLE JSON
    // Loaded via the "Load Sample (Gutterwight)" button in the import modal.
    // Keep in sync with fixtures/gutterwight.json — that file is the canonical
    // tested fixture; this is just the in-modal convenience copy.
    // =========================================================================

    function buildSampleJson() {
        return JSON.stringify({
            // ---- Core stat block ----
            name: "Gutterwight",
            statBlockType: "5.5e",
            monsterType: "undead",
            size: "medium",
            alignment: "neutral evil",
            cr: "5",
            ac: 17,
            acType: "Natural Armor",
            initiativeBonus: "",
            passivePerception: 14,
            hp: 102,
            hpDieCount: 12,
            hpDieValue: 8,
            hpModifier: 48,
            str: 16, dex: 14, con: 18, int: 7, wis: 12, cha: 8,
            savingThrows: ["con", "wis"],
            damageAdjustments: [
                "bludgeoning - resistance",
                "slashing - resistance"
            ],
            conditionImmunities: ["charmed", "poisoned"],
            environments: ["underdark", "urban"],
            gear: "",
            languageNote: "Only languages it knew in life",
            // ---- Rich text ----
            traits: "<p><em><strong>Filth Regeneration.</strong></em> The gutterwight regains 10 hit points at the start of its turn if it is in dim light or darkness, or touching water or sewage. If it takes acid or fire damage, this trait doesn't function until the end of its next turn.</p><p><em><strong>Grate-Creeper.</strong></em> The gutterwight can move through spaces as narrow as 4 inches without squeezing, provided they connect to a drain, grate, or pipe opening.</p><p><em><strong>Stench of the Underflow.</strong></em> A creature that starts its turn within 10 feet of the gutterwight must succeed on a DC 13 Constitution saving throw or be poisoned until the start of its next turn. On a success, the creature is immune to this stench for 24 hours.</p><p><em><strong>Sunshy.</strong></em> While in bright light, the gutterwight has disadvantage on attack rolls.</p>",
            actions: "<p><strong>Multiattack.</strong> The gutterwight makes two Rake attacks.</p><p><em><strong>Rake.</strong></em> <em>Melee Weapon Attack:</em> +6 to hit, reach 5 ft., one target. <em>Hit:</em> 12 (2d8 + 3) slashing damage. If the target is grappled by the gutterwight, the hit deals an additional 7 (2d6) bludgeoning damage.</p><p><em><strong>Hook and Haul (Recharge 5\u20136).</strong></em> <em>Melee Weapon Attack:</em> +6 to hit, reach 10 ft., one creature. <em>Hit:</em> 9 (2d6 + 3) piercing damage and the target must succeed on a DC 14 Strength saving throw or be grappled (escape DC 14) and pulled up to 10 feet toward the gutterwight.</p>",
            bonusActions: "<p><em><strong>Drain-Slip.</strong></em> If the gutterwight is within 5 feet of a drain, grate, or sewer opening, it moves up to half its speed without provoking opportunity attacks.</p>",
            reactions: "",
            characteristics: "<p>A revenant-like horror of sodden rags, clotted hair, and grate-bent iron. It hates light and loves the reek of the undercity. Its elongated limbs move with unsettling fluidity and it speaks only in guttered whispers.</p>",
            isLegendary: false,
            legendaryActions: "",
            isMythic: false,
            mythicActions: "",
            hasLair: false,
            lairDescription: "",
            // ---- Sub-page data (filled on separate pages after main form saves) ----
            senses: [
                { type: "darkvision", notes: "60 ft." }
            ],
            skills: [
                { name: "stealth" },
                { name: "perception" }
            ],
            movement: [
                { type: "walk",  speed: 30 },
                { type: "climb", speed: 20 }
            ],
            languages: [
                { name: "common", notes: "understands but does not speak" }
            ]
        }, null, 2);
    }

    // =========================================================================
    // UI — import button + modal (only injected on main edit page)
    // =========================================================================

    function openImportModal(isCreatePage) {
        document.getElementById('bcn-import-modal')?.remove();

        const overlay = document.createElement('div');
        overlay.id = 'bcn-import-modal';
        overlay.style.cssText = `
            position:fixed;inset:0;background:rgba(0,0,0,0.78);
            z-index:99998;display:flex;align-items:center;justify-content:center;
        `;

        const modal = document.createElement('div');
        modal.style.cssText = `
            background:#1a1e21;border:1px solid #555;border-radius:8px;
            padding:24px;width:720px;max-width:95vw;max-height:90vh;
            display:flex;flex-direction:column;gap:14px;
            color:#ddd;font-family:sans-serif;font-size:14px;
        `;

        const instructions = isCreatePage
            ? `<strong style="color:#beb;">Fill Form Only</strong> — you're on the Create page.
               The script will fill all fields. <strong style="color:#f0ad4e;">Click Save yourself</strong>
               when ready — DnD Beyond will redirect to the edit page, where the script will
               automatically continue to Senses → Skills → Movement → Languages.<br>
               <span style="color:#f0ad4e;">⚠ "Import &amp; Save All" is disabled here because the monster
               doesn't have an ID yet. Use Fill &amp; Continue instead.</span>`
            : `<strong style="color:#beb;">Import &amp; Save All</strong> — fills this form, saves it, then
               automatically visits Senses → Skills → Movement → Languages sub-pages and fills those too,
               then returns here.<br>
               <strong style="color:#beb;">Fill Form Only</strong> — fills this page only, no save or navigation.`;

        modal.innerHTML = `
            <div style="display:flex;justify-content:space-between;align-items:center;">
                <h2 style="margin:0;font-size:19px;color:#fff;">BCN Monster Importer <span style="font-size:13px;color:#888;font-weight:normal;">v2.0</span></h2>
                <button id="bcn-close-btn" style="background:none;border:none;color:#aaa;font-size:26px;cursor:pointer;line-height:1;padding:0 4px;">×</button>
            </div>
            <div style="background:#1e2a1e;border:1px solid #3a5a3a;border-radius:4px;padding:10px 14px;font-size:13px;color:#9db;line-height:1.6;">
                ${instructions}
            </div>
            <textarea id="bcn-json-input" spellcheck="false" style="
                flex:1;min-height:320px;background:#0d1012;color:#cfc;
                border:1px solid #555;border-radius:4px;padding:10px;
                font-family:monospace;font-size:12px;resize:vertical;tab-size:2;
            " placeholder="Paste monster JSON here…"></textarea>
            <div id="bcn-error-msg" style="color:#f88;font-size:12px;min-height:16px;"></div>
            <div style="display:flex;gap:10px;justify-content:flex-end;flex-wrap:wrap;">
                <button id="bcn-sample-btn" style="
                    background:#2a3540;color:#ccc;border:1px solid #555;
                    padding:8px 16px;border-radius:4px;cursor:pointer;font-size:13px;">
                    Load Sample (Gutterwight)
                </button>
                <button id="bcn-fillonly-btn" style="
                    background:#2a3540;color:#ccc;border:1px solid #555;
                    padding:8px 16px;border-radius:4px;cursor:pointer;font-size:13px;">
                    ${isCreatePage ? 'Fill &amp; Continue →' : 'Fill Form Only'}
                </button>
                ${isCreatePage ? '' : `
                <button id="bcn-import-btn" style="
                    background:#1a6b2e;color:#fff;border:none;
                    padding:8px 22px;border-radius:4px;cursor:pointer;
                    font-size:13px;font-weight:700;letter-spacing:.3px;">
                    Import &amp; Save All →
                </button>`}
            </div>
        `;

        overlay.appendChild(modal);
        document.body.appendChild(overlay);

        document.getElementById('bcn-close-btn')
            .addEventListener('click', () => overlay.remove());
        overlay.addEventListener('click', e => { if (e.target === overlay) overlay.remove(); });

        document.getElementById('bcn-sample-btn').addEventListener('click', () => {
            document.getElementById('bcn-json-input').value = buildSampleJson();
            document.getElementById('bcn-error-msg').textContent = '';
        });

        // "Fill Form Only" on edit page, or "Fill & Continue" on create page
        document.getElementById('bcn-fillonly-btn').addEventListener('click', () => {
            const raw = document.getElementById('bcn-json-input').value.trim();
            const errEl = document.getElementById('bcn-error-msg');
            if (!raw) { errEl.textContent = 'Paste your JSON first.'; return; }
            let data;
            try { data = JSON.parse(raw); }
            catch (e) { errEl.textContent = 'Invalid JSON: ' + e.message; return; }
            errEl.textContent = '';
            overlay.remove();
            setTimeout(() => {
                const errs = fillMainForm(data);
                if (isCreatePage) {
                    // Stash the payload so sub-pages run after DnD Beyond redirects
                    // to the edit URL. We don't have a monsterId yet so queue is stored
                    // but navigation won't fire until we land on the edit page.
                    const queue = buildQueue(data);
                    if (queue.length > 0) {
                        const payload = { data, monsterId: null, entityId: null,
                                          editUrl: null, queue, done: [] };
                        savePayload(payload);
                        showBanner('✓ Form filled. Click Save — the script will handle sub-pages after redirect.', '#1a6b2e');
                    } else {
                        showBanner('✓ Form filled. Click Save to create the monster.');
                    }
                } else {
                    if (errs.length) alert('[BCN] Warnings:\n' + errs.map(e => '• ' + e).join('\n'));
                    else showBanner('✓ Form filled. Review and click Save Changes when ready.');
                }
            }, 100);
        });

        // "Import & Save All" — edit page only
        const importBtn = document.getElementById('bcn-import-btn');
        if (importBtn) {
            importBtn.addEventListener('click', () => {
                const raw = document.getElementById('bcn-json-input').value.trim();
                const errEl = document.getElementById('bcn-error-msg');
                if (!raw) { errEl.textContent = 'Paste your JSON first.'; return; }
                let data;
                try { data = JSON.parse(raw); }
                catch (e) { errEl.textContent = 'Invalid JSON: ' + e.message; return; }
                errEl.textContent = '';
                overlay.remove();
                setTimeout(() => startImport(data), 100);
            });
        }
    }

    function injectButton() {
        if (document.getElementById('bcn-import-open-btn')) return;

        const path = window.location.pathname;
        const isCreatePage = path === '/homebrew/creations/create-monster'
                          || path === '/homebrew/creations/create-monster/create';

        const btn = document.createElement('button');
        btn.id = 'bcn-import-open-btn';
        btn.type = 'button';
        btn.textContent = '⬇ Import JSON';
        btn.style.cssText = `
            position:fixed;bottom:24px;right:24px;z-index:99999;
            background:#1a6b2e;color:#fff;border:none;padding:10px 18px;
            border-radius:4px;cursor:pointer;font-size:13px;font-weight:600;
            box-shadow:0 2px 8px rgba(0,0,0,0.4);
        `;
        btn.addEventListener('click', e => {
            e.preventDefault();
            e.stopPropagation();
            openImportModal(isCreatePage);
        });

        // Anchor to the page <header> which exists before TinyMCE touches anything
        // and is completely outside the form DOM. insertAdjacentElement on the header
        // cannot be captured by TinyMCE iframe initialisation.
        const anchor = document.querySelector('header.page-header')
                    || document.querySelector('#site-main')
                    || document.querySelector('#site');
        if (anchor) {
            anchor.insertAdjacentElement('beforebegin', btn);
        } else {
            // True last resort — use a MutationObserver to immediately move it
            // if TinyMCE captures it
            document.body.appendChild(btn);
            new MutationObserver(() => {
                if (btn.parentNode !== document.body) {
                    document.body.appendChild(btn);
                }
            }).observe(document.body, { childList: true, subtree: false });
        }
    }

    // =========================================================================
    // BOOT
    // Determines which page we're on and takes appropriate action.
    // =========================================================================

    function boot() {
        const path = window.location.pathname;

        const isMainForm = path.includes('/homebrew/creations/create-monster')
                        || path.includes('/homebrew/creations/monsters/');
        const isSubPage  = path.includes('/monster/senses/create/')
                        || path.includes('/monster/skills/create/')
                        || path.includes('/monster/movement/create/')
                        || path.includes('/entity/language/create/');

        const payload = loadPayload();

        // --- Sub-page with active import run ---
        if (isSubPage && payload) {
            // Give DnD Beyond time to initialise its form JS
            setTimeout(() => runSubPage(payload), 900);
            return;
        }

        // --- Sub-page without a run (manual navigation) ---
        if (isSubPage) return;

        // --- Main edit/create page ---
        if (isMainForm) {
            injectButton();

            // Returned from all sub-pages successfully
            if (payload && Array.isArray(payload.queue) && payload.queue.length === 0) {
                showBanner('✓ All sub-pages complete! Monster fully imported.');
                clearPayload();
                return;
            }

            // We have a payload but monsterId is null — we just arrived on the edit
            // page after saving from the create page. Extract IDs now and continue.
            if (payload && Array.isArray(payload.queue) && payload.queue.length > 0
                    && !payload.monsterId) {
                const { monsterId, entityId } = extractIds();
                if (monsterId) {
                    payload.monsterId = monsterId;
                    payload.entityId  = entityId;
                    payload.editUrl   = window.location.href;
                    savePayload(payload);
                    showBanner(`✓ Monster saved. Navigating to: ${payload.queue.join(' → ')}…`, '#2c5aa0');
                    setTimeout(() => navigateToNext(payload), 1500);
                } else {
                    setTimeout(() => {
                        const { monsterId: id2, entityId: eid2 } = extractIds();
                        if (id2) {
                            payload.monsterId = id2;
                            payload.entityId  = eid2;
                            payload.editUrl   = window.location.href;
                            savePayload(payload);
                            showBanner(`✓ Monster saved. Navigating to: ${payload.queue.join(' → ')}…`, '#2c5aa0');
                            setTimeout(() => navigateToNext(payload), 1000);
                        } else {
                            showBanner('⚠ Could not extract monster ID. Use Import & Save All manually.', '#c0392b');
                            clearPayload();
                        }
                    }, 2000);
                }
                return;
            }

            // Returning to edit page after a sub-page cycle — navigate to next
            if (payload && Array.isArray(payload.queue) && payload.queue.length > 0) {
                showBanner(`✓ Saved. Navigating to next: ${payload.queue[0]}…`, '#2c5aa0');
                setTimeout(() => navigateToNext(payload), 1200);
                return;
            }

            console.log('[BCN Importer v2] Ready. Click "⬇ Import JSON" to begin.');
        }
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', boot);
    } else {
        boot();
    }

})();
