// ==UserScript==
// @name         DDB Homebrew Monster Importer
// @namespace    https://github.com/wlm2048/ddb-homebrew-monster-importer
// @version      2.0.0
// @description  Import homebrew monsters into DnD Beyond from JSON — main form + Languages/Senses/Skills/Movement sub-pages
// @author       Bill Martin <wlm2048@gmail.com>
// @match        https://www.dndbeyond.com/homebrew/creations/create-monster
// @match        https://www.dndbeyond.com/homebrew/creations/create-monster/create
// @match        https://www.dndbeyond.com/homebrew/creations/monsters/*/edit
// @match        https://www.dndbeyond.com/monster/senses/create/*
// @match        https://www.dndbeyond.com/monster/skills/create/*
// @match        https://www.dndbeyond.com/monster/movement/create/*
// @match        https://www.dndbeyond.com/entity/language/create/*
// @grant        none
// ==/UserScript==

(function () {
    'use strict';

    // !! Generated by build.js — edit files in src/ instead of this file !!

    // Guard against Tampermonkey injecting this multiple times on the same page
    // (happens when TinyMCE editor init triggers extra document events).
    if (window.__ddbImporterLoaded) return;
    window.__ddbImporterLoaded = true;

    // Guard against running inside a TinyMCE iframe — we only want the top frame.
    if (window !== window.top) return;

    // =========================================================================
    // SESSION STORAGE KEY
    // Used to pass the JSON payload across page navigations.
    // =========================================================================
    const SS_KEY = 'ddb_importer_payload';
